### ISSUE TITLE
App.Gettext is not loaded and could not be found

### ISSUE THREAD

**Issue by ai10** [AdamBrodzinski/awesome-stack#1]
== Compilation error on file web/controllers/user_controller.ex ==
*\* (CompileError) web/controllers/user_controller.ex:2: module App.Gettext is not loaded and could not be found

I cloned repository,
mix deps.get
mix phoenix.server 
==Compilation error supra ==
mix deps.compile
mix phoenix.server
==Compilation error supra ==

please advise

**Comment by AdamBrodzinski** [comment]
Oh sorry about that. I removed some files and perhaps I didn't recompile before pushing this up. I removed Gettext because I use Phoenix as an API. However, I didn't remove the [this line](https://github.com/AdamBrodzinski/awesome-stack/blob/master/server/mix.exs#L29) to remove the library as well.

You can either remove that line or if you want gettext, re-add [this file](https://github.com/AdamBrodzinski/awesome-stack/blob/720e716047a0f16b77a525faf54140dd8fbbc45e/server/web/gettext.ex) from [this commit](https://github.com/AdamBrodzinski/awesome-stack/commit/536b20dde35045146990189d2d1c4362a406cdc2)

I've also pushed a new commit removing that lib from the config so re-cloning it should work too.

**Comment by ai10** [comment]
I think there are some residual references that make a simple clone fail as before. I got past the issue by re-adding the getttext app module file.

**Comment by AdamBrodzinski** [comment]
Thanks for your patience @ai10 , I think i've fixed it now (or at least it's working on my end now). The [latest commit](https://github.com/AdamBrodzinski/awesome-stack/commit/95a30471a7910e828c83ea4edd230c365f085fe7) removes the last of the vestiges from Gettext. Also worth noting, when I removed the mix.lock and reran `mix deps.get` it upgraded a few libs. Master should now be working :+1:

**Comment by ai10** [comment]
:stars: thanks;

I'll open another issue for my second difficulty.
