### ISSUE TITLE
Cannot resolve module 'react-router'

### ISSUE THREAD

**Issue by ai10** [AdamBrodzinski/awesome-stack#2]
I'm following the 'Getting started pattern' explained in an earlier repository

cd client
npm install
I get peer dependency WARN flags

npm start

....
{0} [built]
 [1422] ./~/redbox-react/~/object-assign/index.js 896 bytes {0} [built]
 [1423] ./~/redbox-react/lib/lib.js 4.66 kB {0} [built]
 [1424] ./src/pages/Login.js 2.07 kB {0} [built] [3 errors]
 [1425] ./src/reducers/app.js 677 bytes {0} [built]

ERROR in ./src/routes.js
Module not found: Error: Cannot resolve module 'react-router' in /home/max/awesome-stack/client/src
 @ ./src/routes.js 14:19-42

ERROR in ./src/pages/Home.js
Module not found: Error: Cannot resolve module 'react-router' in /home/max/awesome-stack/client/src/pages
 @ ./src/pages/Home.js 21:19-42

ERROR in ./src/pages/Login.js
Module not found: Error: Cannot resolve module 'react-redux' in /home/max/awesome-stack/client/src/pages
 @ ./src/pages/Login.js 21:18-40

ERROR in ./src/pages/Login.js
Module not found: Error: Cannot resolve module 'react-router' in /home/max/awesome-stack/client/src/pages
 @ ./src/pages/Login.js 23:19-42

ERROR in ./src/pages/Login.js
Module not found: Error: Cannot resolve module 'react-router-redux' in /home/max/awesome-stack/client/src/pages
 @ ./src/pages/Login.js 27:24-53

i think the key is to directly install said modules.

**Comment by ai10** [comment]
npm install react-router react-router-redux react-redux
solves

**Comment by AdamBrodzinski** [comment]
Thanks for bringing this up. I though that `"simple-react-redux": "1.0.0"` would bring these in [here](https://github.com/AdamBrodzinski/simple-redux-react/blob/master/package.json#L37-L43). I need to figure out how to add them as peer deps so that it warns you instead. Speaking of that lib, you may want to checkout [issue 1](https://github.com/AdamBrodzinski/simple-redux-react/issues/1) that deals with a naming conflict in the readme. It also currently does not toggle `debug` on master and I just need to push the fix live and release on NPM. That version (1.0.1) also turns devtools off by default and has Ctrl H as a shortcut to open it up.

Hoping to iron out these inconsistencies soon... I pushed this repo live for a friend to use and am currently working on migrating on migrating my prod app to `simple-react-redux` instead of the code it derived from. Let me know if you run into anything else!

**Comment by ai10** [comment]
:tanabata_tree:  thanks for the fruitful work.
