### ISSUE TITLE
Migrate from Meteor? (examples, tutorials, is it even a thing?)

### ISSUE THREAD

**Issue by zeroasterisk** [AdamBrodzinski/awesome-stack#4]
I am totally following you... I've been watching your Elixir work and DDP backfilling as needed and now, perhaps, moving from Meteor to a new platform...

I foresee me (and other) Meteor developers also being interested in this stack, and your opinions on how this compares to the Meteor stack.

With the UI now in React, and state in Redux (i know, not quite) most of what I need Meteor for is server/client sync and tooling... therefore, this could be a great replacement.

I've been looking at other options, including on socket connections, but so far none have the security and auto-state-updating I've been looking for.  Ideally, I'd like it to feel like Meteor; where whatever data I've shared to the client (or that the client has subscribed to) gets auto-updated from changes from the server, and sends changes to the server... all with as little over-the-wire as possible. Bonus points for client changes state (which updates client if needed), sync to server, reconcile state (which updates client if needed).

I looked into PouchDB for a bit, and it's promising, but I haven't seen it at scale yet, esp. not for more complex applications (dozens of collections and chained requests).

**Comment by AdamBrodzinski** [comment]
Hmmm a tutorial on Medium would be kind of cool. Maybe I can write one later on Medium once I get caught up with life. 

By the way thanks for making MeteorRider! It was a linchpin in building Blonk... those were the days!!

The closest competitor to Meteor would be the RethinkDB Horizon product (not sure if it's out yet but should be in public beta at the least)... as it has a very mini-mongo like API.

I've found that building out the wiring in Phoenix didn't take that long once I learned how to do things the 'non-meteor' way with REST calls and JWT authentication (similar to Meteor auth token actually). 

Phoenix channels will give you the security over the socket fairly easily and the JWT can protect REST routes with a plug that checks the routes... for example `/api/admin/` would require that the user role is an admin (either by querying the user doc, similar to the Roles package or by using the JWT creds directly since they're signed). You can also have more find grained control per route if that's needed.

I've also noticed that having _all_ data be reactive is very costly and also at least in my apps, not needed.

For now i've just been using GraphQL and RethinkDB and long poll until their realtime spec is ironed out, then switch to using GraphQL and RethinkDB changefeeds as needed.

Phoenix also provides low level realtime support but is very much a manual process but can be very very scalable especially if you don't need to hit the DB (like displaying if a user if online/offline for ex).

> I foresee me (and other) Meteor developers also being interested in this stack, and your opinions on how this compares to the Meteor stack.

I've noticed that Meteor gets you started very very quickly and then slowly slows you down as you get closer towards the edge of 'the box'. If you go outside the box you need to do some tricky hackery to get things to work, like (historically) PhoneGap & mobile oauth, logging into a 3rd party system, etc..

Phoenix continues to impress me with their [upcoming distributed systems work](https://dockyard.com/blog/2016/03/25/what-makes-phoenix-presence-special-sneak-peek) and OTP is the icing on the cake... it basically handles most scaling issues with ease, and in a fault tolerant/self-healing manner. Actually thinking about it if it wasn't for OTP and the erlang VM I wouldn't use Elixir. Those 2 things are that good.

> With the UI now in React, and state in Redux (i know, not quite) most of what I need Meteor for is server/client sync and tooling... therefore, this could be a great replacement.

I agree. In 2012 dropping script tags and Grunt was great. However, now having Meteor as the build tool is cumbersome and I just need that client/server sync. I also have tended to take out realtime to scale things (like Blonk) which makes it more of a glorified build tool an RPC replacement for AJAX. 

Hope this helps!!

I would also check out my meteor_elixir project and step through the commits to see how to it works a bit more with the manual pub/sub... it's using minimongo but you could imagine using Redux in the same places to store data instead.

**edit** maybe when I have more time I can migrate `react-ive meteor` to Phoenix :smile:
