### ISSUE TITLE
ecto for rethinkdb

### ISSUE THREAD

**Issue by gdub01** [AdamBrodzinski/awesome-stack#6]
What do you think about this: https://github.com/almightycouch/rethinkdb_ecto ? I think the main benefit is it gives version controlled joins for rethink.  Just thought I'd put it on your radar in case you haven't seen it.

**Comment by AdamBrodzinski** [comment]
Thanks @gdub01 !

The main reason for not using Ecto is that I really dislike it's query syntax. Something like https://github.com/robconery/moebius fits me better (for SQL). 

I really like the Ecto Schema but it feels like overkill for my projects, especially if you go the microserver (or umbrella) approach where all DB data is going through the API. If that's the case then GraphQL's schema suffices for me (just rambling and thinking out loud here).

I've been tinkering with a preload helper that's a bit more verbose but works something like:

```
table("posts")
|> DB.Helpers.run
|> DB.Helpers.preload("author", from: "authors")
```

but I haven't had a chance to iron it out yet with different associations. This would basically make two DB calls instead of a single joined query.... which makes it a bit easier with a conditional `author` field in GraphQL. At any rate it needs more work 😄 

Another thing i've added is migrations so those are version controlled... adding tables and indexes as needed so they're version controlled. (need to add it back into this repo too!)

Have you used Ecto with RethinkDB yet?

**Comment by gdub01** [comment]
Right on! I haven't tried Ecto w/ rethink but thought since it's well tested and takes care of migration version control it may be a good idea... but wanted to know your thoughts. That ecto/rethink repo is relatively new so I didn't know if you went with hamiltop's because of lack of choice or by design. Sounds like the latter =) 

Anyways I'm a fan of your helper though... as well as the concept of that umbrella DB api.  Thanks!

**Comment by AdamBrodzinski** [comment]
@gdub01 I've started using a script in `/private` that has migrations for setting up databases/tables/indexes that should help too 👍
